# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100)),
                ('start_block', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('times_seen', models.IntegerField(default=1)),
                ('bssid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeProbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100)),
                ('start_block', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('times_seen', models.IntegerField(default=1)),
                ('mac_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100)),
                ('start_block', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('times_seen', models.IntegerField(default=1)),
                ('mac_address', models.CharField(max_length=100)),
                ('bssid', models.CharField(max_length=100)),
                ('associated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='nodeseen',
            unique_together=set([('sensor', 'start_block', 'mac_address', 'bssid')]),
        ),
        migrations.AlterUniqueTogether(
            name='nodeprobe',
            unique_together=set([('sensor', 'start_block', 'mac_address', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='accesspoint',
            unique_together=set([('sensor', 'start_block', 'bssid')]),
        ),
    ]
