# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='bssid',
            field=models.CharField(max_length=100),
        ),
    ]
